# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/myhstry
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:latest
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - run:
          name: Build
          command: mvn install -Dspring.profiles.active=test
      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
  test:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:latest
    steps:
      - checkout
      - run: mvn dependency:go-offline
      - run:
          name: Test
          command: mvn integration-test -Dspring.profiles.active=test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
          
  deploy:
    working_directory: ~/myhstry
    steps:
      # Prepare for Docker commands
      - setup_remote_docker
      
      # Login to Docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      
      # Build then Push the image to the Docker Respository
      - run: ./mvnw install dockerfile:build -Dspring.profiles.active=test
      - run: ./mvnw install dockerfile:push -Dspring.profiles.active=test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
      - deploy:
        requires:
          - build

      
#      # Prepare for Docker commands
#      - setup_remote_docker
#      
#      # Login to Docker
#      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
#      
#      # Build then Push the image to the Docker Respository
#      - run: ./mvnw install dockerfile:build -Dspring.profiles.active=test
#      - run: ./mvnw install dockerfile:push -Dspring.profiles.active=test
#
#  deploy:
#    docker:
#      - image: circleci/openjdk:8-jdk
#    working_directory: ~/myhstry  
#    steps:
#      - run:
#          name: Deploy if tests pass and branch is Master
#          command: ssh -o "StrictHostKeyChecking no" $USERNAME@$SERVER docker pull andydiack/myhstry